//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.vodataservice.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             A table with sky coverage typically have columns that give
 *             longitude-latitude positions in some coordinate system.  
 *          
 * 
 * <p>Java class for CatalogService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatalogService">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/VODataService/v1.1}DataService">
 *       &lt;sequence>
 *         &lt;element name="tableset" type="{http://www.ivoa.net/xml/VODataService/v1.1}TableSet" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogService", propOrder = {
    "tableset"
})
public class CatalogService
    extends DataService
{

    protected TableSet tableset;

    /**
     * Gets the value of the tableset property.
     * 
     * @return
     *     possible object is
     *     {@link TableSet }
     *     
     */
    public TableSet getTableset() {
        return tableset;
    }

    /**
     * Sets the value of the tableset property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableSet }
     *     
     */
    public void setTableset(TableSet value) {
        this.tableset = value;
    }

}
