//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.vodataservice.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *            This type assumes that it is used in the context of 
 *            implied source (i.e., current) and target tables, as in
 *            the ForeignKey type's fkColumn.
 *          
 * 
 * <p>Java class for FKColumn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FKColumn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromColumn" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="targetColumn" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FKColumn", propOrder = {
    "fromColumn",
    "targetColumn"
})
public class FKColumn {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String fromColumn;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String targetColumn;

    /**
     * Gets the value of the fromColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromColumn() {
        return fromColumn;
    }

    /**
     * Sets the value of the fromColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromColumn(String value) {
        this.fromColumn = value;
    }

    /**
     * Gets the value of the targetColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetColumn() {
        return targetColumn;
    }

    /**
     * Sets the value of the targetColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetColumn(String value) {
        this.targetColumn = value;
    }

}
