//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.vodataservice.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ivoa.xml.vodataservice.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ivoa.xml.vodataservice.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StandardSTC }
     * 
     */
    public StandardSTC createStandardSTC() {
        return new StandardSTC();
    }

    /**
     * Create an instance of {@link TableSchema }
     * 
     */
    public TableSchema createTableSchema() {
        return new TableSchema();
    }

    /**
     * Create an instance of {@link VOTableType }
     * 
     */
    public VOTableType createVOTableType() {
        return new VOTableType();
    }

    /**
     * Create an instance of {@link BaseParam }
     * 
     */
    public BaseParam createBaseParam() {
        return new BaseParam();
    }

    /**
     * Create an instance of {@link FKColumn }
     * 
     */
    public FKColumn createFKColumn() {
        return new FKColumn();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link ParamHTTP }
     * 
     */
    public ParamHTTP createParamHTTP() {
        return new ParamHTTP();
    }

    /**
     * Create an instance of {@link TAPType }
     * 
     */
    public TAPType createTAPType() {
        return new TAPType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link InputParam }
     * 
     */
    public InputParam createInputParam() {
        return new InputParam();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link SimpleDataType }
     * 
     */
    public SimpleDataType createSimpleDataType() {
        return new SimpleDataType();
    }

    /**
     * Create an instance of {@link CatalogService }
     * 
     */
    public CatalogService createCatalogService() {
        return new CatalogService();
    }

    /**
     * Create an instance of {@link Coverage }
     * 
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link ForeignKey }
     * 
     */
    public ForeignKey createForeignKey() {
        return new ForeignKey();
    }

    /**
     * Create an instance of {@link ServiceReference }
     * 
     */
    public ServiceReference createServiceReference() {
        return new ServiceReference();
    }

    /**
     * Create an instance of {@link TableSet }
     * 
     */
    public TableSet createTableSet() {
        return new TableSet();
    }

    /**
     * Create an instance of {@link DataService }
     * 
     */
    public DataService createDataService() {
        return new DataService();
    }

    /**
     * Create an instance of {@link DataCollection }
     * 
     */
    public DataCollection createDataCollection() {
        return new DataCollection();
    }

    /**
     * Create an instance of {@link TableParam }
     * 
     */
    public TableParam createTableParam() {
        return new TableParam();
    }

}
