//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.vodataservice.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *             This set is intended for describing simple input parameters to 
 *             a service or function.
 *          
 * 
 * <p>Java class for SimpleDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleDataType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://www.ivoa.net/xml/VODataService/v1.1>DataType">
 *       &lt;attribute name="arraysize" type="{http://www.ivoa.net/xml/VODataService/v1.1}ArrayShape" default="1" />
 *       &lt;attribute name="delim" type="{http://www.w3.org/2001/XMLSchema}string" default=" " />
 *       &lt;attribute name="extendedType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="extendedSchema" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleDataType")
public class SimpleDataType
    extends DataType
{


}
