//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for angleUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="angleUnitType">
 *   &lt;restriction base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}unitType">
 *     &lt;enumeration value="deg"/>
 *     &lt;enumeration value="rad"/>
 *     &lt;enumeration value="h"/>
 *     &lt;enumeration value="arcmin"/>
 *     &lt;enumeration value="arcsec"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "angleUnitType")
@XmlEnum
public enum AngleUnitType {

    @XmlEnumValue("deg")
    DEG("deg"),
    @XmlEnumValue("rad")
    RAD("rad"),
    @XmlEnumValue("h")
    H("h"),
    @XmlEnumValue("arcmin")
    ARCMIN("arcmin"),
    @XmlEnumValue("arcsec")
    ARCSEC("arcsec");
    private final String value;

    AngleUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AngleUnitType fromValue(String v) {
        for (AngleUnitType c: AngleUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
