//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Box shape: a rectangle defined by its center and size on both dimensions; since it is a polygon, it is redundant, but simple rectangles with great circle sides are awkward to define in spherical coordinates
 * 
 * <p>Java class for boxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="boxType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}shapeType">
 *       &lt;sequence>
 *         &lt;element name="Center" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double2Type"/>
 *         &lt;element name="Size" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double2Type"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boxType", propOrder = {
    "center",
    "size"
})
public class BoxType
    extends ShapeType
{

    @XmlElement(name = "Center", required = true, nillable = true)
    protected Double2Type center;
    @XmlElement(name = "Size", required = true, nillable = true)
    protected Double2Type size;

    /**
     * Gets the value of the center property.
     * 
     * @return
     *     possible object is
     *     {@link Double2Type }
     *     
     */
    public Double2Type getCenter() {
        return center;
    }

    /**
     * Sets the value of the center property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double2Type }
     *     
     */
    public void setCenter(Double2Type value) {
        this.center = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Double2Type }
     *     
     */
    public Double2Type getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double2Type }
     *     
     */
    public void setSize(Double2Type value) {
        this.size = value;
    }

}
