//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Abstact coordinate interval type
 * 
 * <p>Java class for coordIntervalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coordIntervalType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}stcBaseType">
 *       &lt;attribute name="lo_include" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="hi_include" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="fill_factor" type="{http://www.w3.org/2001/XMLSchema}float" default="1.0" />
 *       &lt;attribute name="frame_id" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coordIntervalType")
@XmlSeeAlso({
    Coord3VecIntervalType.class,
    UCoordScalarIntervalType.class,
    UCoord3VecIntervalType.class,
    Coord2VecIntervalType.class,
    UCoord2VecIntervalType.class,
    TimeIntervalType.class,
    SpatialIntervalType.class,
    CoordScalarIntervalType.class
})
public class CoordIntervalType
    extends StcBaseType
{

    @XmlAttribute(name = "lo_include")
    protected Boolean loInclude;
    @XmlAttribute(name = "hi_include")
    protected Boolean hiInclude;
    @XmlAttribute(name = "fill_factor")
    protected Float fillFactor;
    @XmlAttribute(name = "frame_id")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object frameId;

    /**
     * Gets the value of the loInclude property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLoInclude() {
        if (loInclude == null) {
            return true;
        } else {
            return loInclude;
        }
    }

    /**
     * Sets the value of the loInclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoInclude(Boolean value) {
        this.loInclude = value;
    }

    /**
     * Gets the value of the hiInclude property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHiInclude() {
        if (hiInclude == null) {
            return true;
        } else {
            return hiInclude;
        }
    }

    /**
     * Sets the value of the hiInclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHiInclude(Boolean value) {
        this.hiInclude = value;
    }

    /**
     * Gets the value of the fillFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getFillFactor() {
        if (fillFactor == null) {
            return  1.0F;
        } else {
            return fillFactor;
        }
    }

    /**
     * Sets the value of the fillFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFillFactor(Float value) {
        this.fillFactor = value;
    }

    /**
     * Gets the value of the frameId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFrameId() {
        return frameId;
    }

    /**
     * Sets the value of the frameId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFrameId(Object value) {
        this.frameId = value;
    }

}
