//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A vector of 2 doubles; components are now separated.
 * 
 * <p>Java class for double2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="double2Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}stcBaseType">
 *       &lt;sequence>
 *         &lt;element name="C1" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double1Type"/>
 *         &lt;element name="C2" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double1Type"/>
 *       &lt;/sequence>
 *       &lt;attribute name="unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}posUnitType" />
 *       &lt;attribute name="vel_time_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}velTimeUnitType" />
 *       &lt;attribute name="gen_unit" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}unitType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "double2Type", propOrder = {
    "c1",
    "c2"
})
@XmlSeeAlso({
    Size2Type.class
})
public class Double2Type
    extends StcBaseType
{

    @XmlElement(name = "C1", required = true, nillable = true)
    protected Double1Type c1;
    @XmlElement(name = "C2", required = true, nillable = true)
    protected Double1Type c2;
    @XmlAttribute(name = "unit")
    protected String unit;
    @XmlAttribute(name = "vel_time_unit")
    protected VelTimeUnitType velTimeUnit;
    @XmlAttribute(name = "gen_unit")
    protected String genUnit;

    /**
     * Gets the value of the c1 property.
     * 
     * @return
     *     possible object is
     *     {@link Double1Type }
     *     
     */
    public Double1Type getC1() {
        return c1;
    }

    /**
     * Sets the value of the c1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double1Type }
     *     
     */
    public void setC1(Double1Type value) {
        this.c1 = value;
    }

    /**
     * Gets the value of the c2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double1Type }
     *     
     */
    public Double1Type getC2() {
        return c2;
    }

    /**
     * Sets the value of the c2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double1Type }
     *     
     */
    public void setC2(Double1Type value) {
        this.c2 = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the velTimeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link VelTimeUnitType }
     *     
     */
    public VelTimeUnitType getVelTimeUnit() {
        return velTimeUnit;
    }

    /**
     * Sets the value of the velTimeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link VelTimeUnitType }
     *     
     */
    public void setVelTimeUnit(VelTimeUnitType value) {
        this.velTimeUnit = value;
    }

    /**
     * Gets the value of the genUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenUnit() {
        return genUnit;
    }

    /**
     * Sets the value of the genUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenUnit(String value) {
        this.genUnit = value;
    }

}
