//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * FK[45] type: needs an equinox
 * 
 * <p>Java class for fkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fkType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}spaceRefFrameType">
 *       &lt;sequence>
 *         &lt;element name="Equinox" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordEquinoxType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fkType", propOrder = {
    "equinox"
})
public class FkType
    extends SpaceRefFrameType
{

    @XmlElement(name = "Equinox", required = true, nillable = true)
    protected String equinox;

    /**
     * Gets the value of the equinox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquinox() {
        return equinox;
    }

    /**
     * Sets the value of the equinox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquinox(String value) {
        this.equinox = value;
    }

}
