//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An area on the unit sphere defined by the intersection with a plane
 * 
 * <p>Java class for halfspaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="halfspaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Vector" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double3Type"/>
 *         &lt;element name="Offset" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}hsOffsetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "halfspaceType", propOrder = {
    "vector",
    "offset"
})
public class HalfspaceType {

    @XmlElement(name = "Vector", required = true, nillable = true)
    protected Double3Type vector;
    @XmlElement(name = "Offset")
    protected double offset;

    /**
     * Gets the value of the vector property.
     * 
     * @return
     *     possible object is
     *     {@link Double3Type }
     *     
     */
    public Double3Type getVector() {
        return vector;
    }

    /**
     * Sets the value of the vector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double3Type }
     *     
     */
    public void setVector(Double3Type value) {
        this.vector = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     */
    public double getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(double value) {
        this.offset = value;
    }

}
