//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for observational STC metadata
 * 
 * <p>Java class for obsDataLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="obsDataLocationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}stcMetadataType">
 *       &lt;sequence>
 *         &lt;element name="ObservatoryLocation" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}observatoryLocationType"/>
 *         &lt;element name="ObservationLocation" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}astroSTCDescriptionType"/>
 *         &lt;element name="PixelSpace" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}pixelSpaceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obsDataLocationType", propOrder = {
    "observatoryLocation",
    "observationLocation",
    "pixelSpace"
})
public class ObsDataLocationType
    extends StcMetadataType
{

    @XmlElement(name = "ObservatoryLocation", required = true, nillable = true)
    protected ObservatoryLocationType observatoryLocation;
    @XmlElement(name = "ObservationLocation", required = true, nillable = true)
    protected AstroSTCDescriptionType observationLocation;
    @XmlElementRef(name = "PixelSpace", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<PixelSpaceType> pixelSpace;

    /**
     * Gets the value of the observatoryLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ObservatoryLocationType }
     *     
     */
    public ObservatoryLocationType getObservatoryLocation() {
        return observatoryLocation;
    }

    /**
     * Sets the value of the observatoryLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservatoryLocationType }
     *     
     */
    public void setObservatoryLocation(ObservatoryLocationType value) {
        this.observatoryLocation = value;
    }

    /**
     * Gets the value of the observationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link AstroSTCDescriptionType }
     *     
     */
    public AstroSTCDescriptionType getObservationLocation() {
        return observationLocation;
    }

    /**
     * Sets the value of the observationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AstroSTCDescriptionType }
     *     
     */
    public void setObservationLocation(AstroSTCDescriptionType value) {
        this.observationLocation = value;
    }

    /**
     * Gets the value of the pixelSpace property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PixelSpaceType }{@code >}
     *     
     */
    public JAXBElement<PixelSpaceType> getPixelSpace() {
        return pixelSpace;
    }

    /**
     * Sets the value of the pixelSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PixelSpaceType }{@code >}
     *     
     */
    public void setPixelSpace(JAXBElement<PixelSpaceType> value) {
        this.pixelSpace = value;
    }

}
