//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * The pixel coordinates type
 * 
 * <p>Java class for pixelCoordsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pixelCoordsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}coordsType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Pixel"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pixelCoordsType", propOrder = {
    "pixel"
})
public class PixelCoordsType
    extends CoordsType
{

    @XmlElementRef(name = "Pixel", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends CoordinateType>> pixel;

    /**
     * Gets the value of the pixel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pixel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPixel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PixelVector3CoordinateType }{@code >}
     * {@link JAXBElement }{@code <}{@link PixelVector1CoordinateType }{@code >}
     * {@link JAXBElement }{@code <}{@link CoordinateType }{@code >}
     * {@link JAXBElement }{@code <}{@link PixelVector2CoordinateType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends CoordinateType>> getPixel() {
        if (pixel == null) {
            pixel = new ArrayList<JAXBElement<? extends CoordinateType>>();
        }
        return this.pixel;
    }

}
