//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * A type that just holds a 1-3D pixel value
 * 
 * <p>Java class for pixelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pixelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}Pixel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pixelType", propOrder = {
    "pixel"
})
public class PixelType {

    @XmlElementRef(name = "Pixel", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class)
    protected JAXBElement<? extends CoordinateType> pixel;

    /**
     * Gets the value of the pixel property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PixelVector3CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PixelVector1CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PixelVector2CoordinateType }{@code >}
     *     
     */
    public JAXBElement<? extends CoordinateType> getPixel() {
        return pixel;
    }

    /**
     * Sets the value of the pixel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PixelVector3CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PixelVector1CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CoordinateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PixelVector2CoordinateType }{@code >}
     *     
     */
    public void setPixel(JAXBElement<? extends CoordinateType> value) {
        this.pixel = value;
    }

}
