//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * smallCircleType indicates in polygons that side is along small circle; with optional pole
 * 
 * <p>Java class for smallCircleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="smallCircleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pole" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double2Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "smallCircleType", propOrder = {
    "pole"
})
public class SmallCircleType {

    @XmlElementRef(name = "Pole", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<Double2Type> pole;

    /**
     * Gets the value of the pole property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double2Type }{@code >}
     *     
     */
    public JAXBElement<Double2Type> getPole() {
        return pole;
    }

    /**
     * Sets the value of the pole property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double2Type }{@code >}
     *     
     */
    public void setPole(JAXBElement<Double2Type> value) {
        this.pole = value;
    }

}
