//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for STC Coordinate
 * 
 * <p>Java class for STCCoordinate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STCCoordinate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}stcMetadataType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}AstroCoordSystem"/>
 *         &lt;element ref="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}AstroCoords"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STCCoordinate", propOrder = {
    "astroCoordSystem",
    "astroCoords"
})
public class STCCoordinate
    extends StcMetadataType
{

    @XmlElement(name = "AstroCoordSystem", required = true, nillable = true)
    protected AstroCoordSystemType astroCoordSystem;
    @XmlElement(name = "AstroCoords", required = true, nillable = true)
    protected AstroCoordsType astroCoords;

    /**
     * Gets the value of the astroCoordSystem property.
     * 
     * @return
     *     possible object is
     *     {@link AstroCoordSystemType }
     *     
     */
    public AstroCoordSystemType getAstroCoordSystem() {
        return astroCoordSystem;
    }

    /**
     * Sets the value of the astroCoordSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link AstroCoordSystemType }
     *     
     */
    public void setAstroCoordSystem(AstroCoordSystemType value) {
        this.astroCoordSystem = value;
    }

    /**
     * Gets the value of the astroCoords property.
     * 
     * @return
     *     possible object is
     *     {@link AstroCoordsType }
     *     
     */
    public AstroCoordsType getAstroCoords() {
        return astroCoords;
    }

    /**
     * Sets the value of the astroCoords property.
     * 
     * @param value
     *     allowed object is
     *     {@link AstroCoordsType }
     *     
     */
    public void setAstroCoords(AstroCoordsType value) {
        this.astroCoords = value;
    }

}
