//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for standard reference positions
 * 
 * <p>Java class for stdRefPosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stdRefPosType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}referencePositionType">
 *       &lt;sequence>
 *         &lt;element name="PlanetaryEphem" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}planetaryEphemType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stdRefPosType", propOrder = {
    "planetaryEphem"
})
public class StdRefPosType
    extends ReferencePositionType
{

    @XmlElementRef(name = "PlanetaryEphem", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<PlanetaryEphemType> planetaryEphem;

    /**
     * Gets the value of the planetaryEphem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PlanetaryEphemType }{@code >}
     *     
     */
    public JAXBElement<PlanetaryEphemType> getPlanetaryEphem() {
        return planetaryEphem;
    }

    /**
     * Sets the value of the planetaryEphem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PlanetaryEphemType }{@code >}
     *     
     */
    public void setPlanetaryEphem(JAXBElement<PlanetaryEphemType> value) {
        this.planetaryEphem = value;
    }

}
