//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 *  2-D coordinate interval type
 * 
 * <p>Java class for vel2VecIntervalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vel2VecIntervalType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}velocityIntervalType">
 *       &lt;sequence>
 *         &lt;element name="LoLimit2Vec" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double2Type" minOccurs="0"/>
 *         &lt;element name="HiLimit2Vec" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double2Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vel2VecIntervalType", propOrder = {
    "loLimit2Vec",
    "hiLimit2Vec"
})
public class Vel2VecIntervalType
    extends VelocityIntervalType
{

    @XmlElementRef(name = "LoLimit2Vec", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<Double2Type> loLimit2Vec;
    @XmlElementRef(name = "HiLimit2Vec", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<Double2Type> hiLimit2Vec;

    /**
     * Gets the value of the loLimit2Vec property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double2Type }{@code >}
     *     
     */
    public JAXBElement<Double2Type> getLoLimit2Vec() {
        return loLimit2Vec;
    }

    /**
     * Sets the value of the loLimit2Vec property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double2Type }{@code >}
     *     
     */
    public void setLoLimit2Vec(JAXBElement<Double2Type> value) {
        this.loLimit2Vec = value;
    }

    /**
     * Gets the value of the hiLimit2Vec property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double2Type }{@code >}
     *     
     */
    public JAXBElement<Double2Type> getHiLimit2Vec() {
        return hiLimit2Vec;
    }

    /**
     * Sets the value of the hiLimit2Vec property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double2Type }{@code >}
     *     
     */
    public void setHiLimit2Vec(JAXBElement<Double2Type> value) {
        this.hiLimit2Vec = value;
    }

}
