//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 11:45:54 AM CET 
//


package net.ivoa.xml.stc.stc_v1_30;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Vertex is a position with optional SmallCircle element; the SmallCircle element indicates that the polygon side formed by that vertex and its predecessor vertex is a small circle, rather than a great circle; SmallCircle has no meaning in Cartesian coordinates
 * 
 * <p>Java class for vertexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vertexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Position" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}double2Type"/>
 *         &lt;element name="SmallCircle" type="{http://www.ivoa.net/xml/STC/stc-v1.30.xsd}smallCircleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vertexType", propOrder = {
    "position",
    "smallCircle"
})
public class VertexType {

    @XmlElement(name = "Position", required = true, nillable = true)
    protected Double2Type position;
    @XmlElementRef(name = "SmallCircle", namespace = "http://www.ivoa.net/xml/STC/stc-v1.30.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<SmallCircleType> smallCircle;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Double2Type }
     *     
     */
    public Double2Type getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double2Type }
     *     
     */
    public void setPosition(Double2Type value) {
        this.position = value;
    }

    /**
     * Gets the value of the smallCircle property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SmallCircleType }{@code >}
     *     
     */
    public JAXBElement<SmallCircleType> getSmallCircle() {
        return smallCircle;
    }

    /**
     * Sets the value of the smallCircle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SmallCircleType }{@code >}
     *     
     */
    public void setSmallCircle(JAXBElement<SmallCircleType> value) {
        this.smallCircle = value;
    }

}
